baseURL = 'https://tedslocum.com/'
languageCode = 'en-us'
title = 'Ted Slocum'
theme = "ink"
paginate = 5

[params]
	subtitle = "Absurdity, gambling, mindfulness, programming, golf, well-being, and my opinions."

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/sted9000"
